orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
version: 2.1
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: sampleapp
          arguments: '--profile assume_role'
          bundle-bucket: sampleappraj
          bundle-key: myS3BucketKey
          deployment-group: sampleapp
          service-role-arn: arn:aws:iam::978016941027:role/sampleappdeploy
