---
- name: Install Rails Server
  hosts: Dev
  # After initial provisioning, use deploy instead of root
  remote_user: root
  # remote_user: deploy
  # become: yes
  # become_method: sudo
  gather_facts: no # don't gather facts because /usr/bin/python isn't set
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
  roles:
#    - common
    - deploy-user
#    - mysql
#    - nginx
#    - certbot
#    - ruby
    - rails
#    - monit
#    - memcached
#    - redis
#    - elasticsearch
    - cloudwatch       
    - sidekiq
